apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: password
