apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: loretta-bank/transaction-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: transaction-service-config
        - secretRef:
            name: transaction-service-secrets
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://<postgres-host>:5432/accountdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
