apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: loretta-bank/account-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: account-service-config
        - secretRef:
            name: account-service-secrets
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://localhost:5432/lorettabank
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: account-service-secrets
              key: datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: account-service-secrets
              key: datasource-password
