apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
type: Opaque
data:
  datasource-username: cG9zdGdyZXM=  # base64 encoded "postgres"
  datasource-password: cGFzc3dvcmQ=  # base64 encoded "password"
