version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  account-service:
    image: account-service:latest
    container_name: account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  transaction-service:
    image: transaction-service:latest
    container_name: transaction-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  loan-service:
    image: your-docker-repo/loan-service:latest
    container_name: loan-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8084:8080"
    depends_on:
      - postgres

  card-service:
    image: card-service:latest
    container_name: card-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8085:8080"
    depends_on:
      - postgres

  customer-support-service:
    image: customer-support-service:latest
    container_name: customer-support-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lorettabank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8086:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
