apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  labels:
    app: card-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
      - name: card-service
        image: loretta-bank/card-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: card-service-config
        - secretRef:
            name: card-service-secrets
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://<postgres-host>:5432/lorettabank
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
