apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loretta-bank.fullname" . }}-config
  labels:
    {{- include "loretta-bank.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.db.host | default "postgres" }}:{{ .Values.db.port | default "5432" }}/{{ .Values.db.name | default "lorettabank" }}
        username: {{ .Values.db.username | default "postgres" }}
        password: {{ .Values.db.password | default "password" }}
      neo4j:
        uri: bolt://{{ .Values.neo4j.host | default "neo4j" }}:{{ .Values.neo4j.port | default "7687" }}
        authentication:
          username: {{ .Values.neo4j.username | default "neo4j" }}
          password: {{ .Values.neo4j.password | default "password" }}
        database: {{ .Values.neo4j.database | default "lorettabank" }}
