apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "loretta-bank.fullname" . }}
  labels:
    {{- include "loretta-bank.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Other NGINX ingress annotations can be added here
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "loretta-bank.fullname" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
