apiVersion: v1
kind: Service
metadata:
  name: {{ include "loretta-bank.fullname" . }}
  labels:
    {{- include "loretta-bank.labels" . | nindent 4 }}
spec:
  type: ClusterIP # Change to LoadBalancer if you need external access
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "loretta-bank.selectorLabels" . | nindent 4 }}
