replicaCount: 1

image:
  repository: "loretta-bank"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: loretta-bank
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: lorettabank.com
      paths: ["/"]

spring:
  profiles:
    active: "prod"

db:
  host: "postgres"
  port: 5432
  name: "lorettabank"
  username: "postgres"
  password: "password"

neo4j:
  host: "neo4j"
  port: 7687
  database: "lorettabank"
  username: "neo4j"
  password: "password"
