apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-support-service
  template:
    metadata:
      labels:
        app: customer-support-service
    spec:
      containers:
      - name: customer-support-service
        image: your-docker-repo/customer-support-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://<postgres-host>:5432/customersupportdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
